### PR TITLE
Recompute INFO fields on sample selection

### LINKED ISSUE #45: Recompute INFO/AC INFO/AN when samples specified.
bcftools recomputes some INFO fields after subsetting by samples. We need to do what it does.

See also this option:
```
-I, --no-update
do not (re)calculate INFO fields for the subset (currently INFO/AC and INFO/AN)
```

### PR DESCRIPTION
**Pull request by Will-Tyler**
### Overview

In bcftools, if the user provides a sample selection, bcftools (re)calculates the AN and AC INFO fields. If the user specifies an empty sample selection, bcftools recomputes the AC and AN INFO fields using the genotypes from all samples. This pull request implements the same behavior.

This pull request closes #45 and #78.

### Testing

I add some validation tests. There were some inaccurate AC and AN fields in the sample VCF at `20:1234567`. bcftools uses the original INFO fields if they are present, whereas this implementation in vcztools does not. Let me know if I should adjust this. I update the sample VCF in this PR so that the AC and AN values are consistent with the genotypes.

### References

- [bcftools view](https://samtools.github.io/bcftools/bcftools.html#view)
  - The `--no-update` option is relevant.

### CODE REVIEW

**Comment by Will-Tyler** [comment]
### Performance tests

```
time vcztools view ../vcf-zarr-publication/scaling/data/chr21_10_4.zarr --no-update -s '' > /dev/null
vcztools view ../vcf-zarr-publication/scaling/data/chr21_10_4.zarr --no-updat  19.20s user 3.31s system 249% cpu 9.028 total
```

```
time vcztools view ../vcf-zarr-publication/scaling/data/chr21_10_4.zarr -s '' > /dev/null 
vcztools view ../vcf-zarr-publication/scaling/data/chr21_10_4.zarr -s '' >   38.59s user 9.29s system 135% cpu 35.239 total
```

```
time vcztools view ../vcf-zarr-publication/scaling/data/chr21_10_5.zarr --no-update -s '' > /dev/null
vcztools view ../vcf-zarr-publication/scaling/data/chr21_10_5.zarr --no-updat  466.06s user 85.65s system 239% cpu 3:50.39 total
```

```
time vcztools view ../vcf-zarr-publication/scaling/data/chr21_10_5.zarr -s '' > /dev/null
vcztools view ../vcf-zarr-publication/scaling/data/chr21_10_5.zarr -s '' >   840.93s user 561.22s system 100% cpu 23:15.66 total
```

### Discussion

Recomputing the INFO fields does indeed slow the program down quite a bit. I will try recomputing the INFO fields by accessing the sample chunks individually instead of all at once as the current implementation does.

**Comment by Will-Tyler** [comment]
I tried accessing the GT NumPy array in sample-wise chunks, but that didn't seem to help at all. Not sure if there is a better way to do the calculations.

**Comment by Will-Tyler** [comment]
Created an issue!

**Comment by jeromekelleher** [comment]
I'm happy to merge this - do you want to take a look @tomwhite?

**Review by tomwhite — APPROVED** [review]

**Pull request merged**
